return {}
--return {
--    "stevearc/overseer.nvim",
--    opts = {},
--    branch = "master",
--    config = function()
--        local overseer = require("overseer")
--        overseer.setup({
--            dap = false,
--            templates = { "builtin", "user.run_script" },
--            strategy = { "toggleterm", use_shell = false, open_on_start = true },
--        })
--        overseer.add_template_hook({
--            module = "^python$|^cargo$",
--        }, function(task_defn, util)
--            util.add_component(task_defn, { "unique", replace = false })
--        end)
--        vim.api.nvim_create_user_command("WatchRun", function()
--            overseer.run_template({ name = "run script" }, function(task)
--                if task then
--                    local main_win = vim.api.nvim_get_current_win()
--                    task:add_component({ "restart_on_save", paths = { vim.fn.expand("%:p") } })
--                    overseer.run_action(task, "open vsplit")
--                    vim.api.nvim_set_current_win(main_win)
--                else
--                    vim.notify("WatchRun not supported for filetype " .. vim.bo.filetype, vim.log.levels.ERROR)
--                end
--            end)
--        end, {})
--        vim.keymap.set("n", "<leader>ow", ":WatchRun<cr>", { desc = "Put file to run on save" })
--    end,
--}
--
--
--
----File to put inside \nvim\lua\overseer\template\user\run_script.lua
--return {
--	name = "run script",
--	builder = function()
--		local file = vim.fn.expand("%:p")
--		local cmd = { file }
--		if vim.bo.filetype == "python" then
--			cmd = { "python", file }
--		elseif vim.bo.filetype == "rust" then
--			vim.cmd(":cd %:h")
--			cmd = { "cargo", "run" }
--		elseif vim.bo.filetype == "go" then
--			cmd = { "go", "run", file }
--		end
--		return {
--			cmd = cmd,
--			components = {
--				{ "on_complete_notify", statuses = { "SUCCESS" } },
--				"unique",
--				--{ "open_output", direction = "vertical", focus = false},
--				"default",
--			},
--		}
--	end,
--	condition = {
--		filetype = { "python", "go", "rust" },
--	},
--}
